name: Docker Example

on: pull_request

jobs:

 code-quality:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.1
   - name: Setup Node.js environment
     uses: actions/setup-node@v6.0.0
   - name: Install dependencies
     run: npm install
   - name: Run Lint
     run: npm run lint
   - name: Run format check
     run: npm run format:check
     
 NPM-tests:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v5.0.1
   - name: Setup Node.js environment
     uses: actions/setup-node@v6.0.0
   - name: Install dependencies
     run: npm install
   - name: Run tests
     run: npm test
   - name: Test Reporter
     uses: dorny/test-reporter@v2.1.1
     with:
      name: JUnit-Tests
      path: '*.xml'
      reporter: jest-junit
   - name: Archive production artifacts
     if: ${{ success() }}
     uses: actions/upload-artifact@v4
     with:
      name: results
      path: .
   - name: Login to Docker Hub
     uses: docker/login-action@v3
     with:
      username: ${{ vars.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASS }}
   -  name: Set up QEMU
      uses: docker/setup-qemu-action@v3
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3
   - name: Build and push
     uses: docker/build-push-action@v6
     with:
      push: true
      tags: vdsjspr/vds:latest
      
   - name: Create comment
     id: gac
     uses: peter-evans/create-or-update-comment@v5
     with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          A new ${{github.event.action}} request has been made on ${{ github.ref_name }} branch.
        reactions: rocket

   - name: Update comment
     if: ${{ success() }}
     uses: peter-evans/create-or-update-comment@v5
     with:
        comment-id: ${{ steps.gac.outputs.comment-id }}
        body: |
          It was a success!
        edit-mode: append
        
   - name: Update comment
     if: ${{ !success() }}
     uses: peter-evans/create-or-update-comment@v5
     with:
        comment-id: ${{ steps.gac.outputs.comment-id }}
        body: |
          It failed!
        edit-mode: append
